#!/usr/bin/bash
#NOTE: don't use this (right now), currently having issues with all request
#timing out when activating the server via a systemd socket

#currently just running the server directly
proj_home=$(git rev-parse --show-toplevel)
echo $proj_home
(cd $proj_home/sniper && cargo build)
(cd $proj_home/sniper-client && cargo build)
bin_path="$proj_home/target/debug"
echo $bin_path
chmod +x $bin_path/sniper
systemd-run --user --socket-property=ListenStream=/tmp/sniper.socket --working-dir=$bin_path $bin_path/sniper
#echo $bin_path